<?php ?>
<section class="code-samples">
<h3 class="h3">Code Syntax Highlighting</h3>
<div class="cf">
  <div class="prism-dark w-1v2">
  <h4 class="h4">dark variation &#8211; <?php echo $theme; ?></h4>
    <pre class="language-css"><code class="language-css" data-language="css"><span class="token comment" spellcheck="true">/* comment */</span><span class="token lf">
</span><span class="token selector">h1 </span><span class="token punctuation">{</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/font-size" target="_blank">font-size</a><span class="token punctuation">:</span> <span class="token number">2</span>em<span class="token punctuation">;</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/margin" target="_blank">margin</a><span class="token punctuation">:</span> <span class="token number">0.67</span>em <span class="token number">0</span><span class="token punctuation">;</span><span class="token lf">
</span><span class="token punctuation">}</span><span class="token lf">
</span><span class="token selector">mark </span><span class="token punctuation">{</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/background" target="_blank">background</a><span class="token punctuation">:</span> <span class="token hexcode">#ff0</span><span class="token punctuation">;</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/color" target="_blank">color</a><span class="token punctuation">:</span> <span class="token hexcode">#000</span><span class="token punctuation">;</span><span class="token lf">
</span><span class="token punctuation">}</span><span class="token lf">
</span><span class="token selector">small </span><span class="token punctuation">{</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/font-size" target="_blank">font-size</a><span class="token punctuation">:</span> <span class="token number">80%</span> <span class="token important">!important</span><span class="token punctuation">;</span><span class="token lf">
</span><span class="token punctuation">}</span></code></pre>
  </div>

  <div class="prism-light w-1v2">
<h4 class="h4">light variation &#8211; <?php echo $theme; ?></h4>
    <pre class="language-css"><code class="language-css" data-language="css"><span class="token comment" spellcheck="true">/* comment */</span><span class="token lf">
</span><span class="token selector">h1 </span><span class="token punctuation">{</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/font-size" target="_blank">font-size</a><span class="token punctuation">:</span> <span class="token number">2</span>em<span class="token punctuation">;</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/margin" target="_blank">margin</a><span class="token punctuation">:</span> <span class="token number">0.67</span>em <span class="token number">0</span><span class="token punctuation">;</span><span class="token lf">
</span><span class="token punctuation">}</span><span class="token lf">
</span><span class="token selector">mark </span><span class="token punctuation">{</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/background" target="_blank">background</a><span class="token punctuation">:</span> <span class="token hexcode">#ff0</span><span class="token punctuation">;</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/color" target="_blank">color</a><span class="token punctuation">:</span> <span class="token hexcode">#000</span><span class="token punctuation">;</span><span class="token lf">
</span><span class="token punctuation">}</span><span class="token lf">
</span><span class="token selector">small </span><span class="token punctuation">{</span><span class="token lf">
</span>  <a class="token property" href="http://docs.webplatform.org/wiki/css/properties/font-size" target="_blank">font-size</a><span class="token punctuation">:</span> <span class="token number">80%</span> <span class="token important">!important</span><span class="token punctuation">;</span><span class="token lf">
</span><span class="token punctuation">}</span></code></pre>
  </div>
</div>
</section>
<?php ?>
