<?php ?><div class="content has-themes-hidden" id="content"><div class="row row-intro">

<div class="section-text">
<p class="intro">Base2Tone colorschemes are created from two base hues, into (32) values with different saturation and lightness levels. Base2Tone is based on <a href="http://simurai.com/projects/2016/01/01/duotone-themes">DuoTone themes</a> by <a href="http://simurai.com/">Simurai</a> for Atom:</p>

<blockquote class="quote"><p>&hellip; It <strong>tones down</strong> less important parts (like punctuation and brackets) and highlights only the <strong>important</strong> ones. This leads to a more calm color scheme, but still lets you find the stuff you’re looking for.</p></blockquote>

<p>Colorschemes are generated with the help of <a href="https://github.com/base16-builder/base16-builder">Base16 Builder</a></p>

</div>

<div class="section-text">
<h3>Dependencies</h3>
<p>Some customized commands from the latest fork of Base16 Builder can be found here in executable bash scripts (`cli/io.sh`). Read more on this versatile and flexible <abbr title="Command Line Interface">CLI</abbr> building tool <a href="https://github.com/base16-builder/base16-builder">on the Github repo for Base16 Builder</a>, and the many ways to use it from the command-line.</p>
</div>

<div class="section-text">
<h3>Installation</h3>
<p>Base16 Builder is available on NPM<sup>[1]</sup>, you can install it on your machine like so from the commandline:</p>

<pre class="language-bash"><code class="language-bash" data-language="bash">
$ npm install --global base16-builder
</code></pre>

</div>

<p>Use these colorschemes to generate syntax-highlighting themes (TODO: _for many applications_):</p>

<p><a href="https://github.com/atelierbram/Base2Tone-prism">Prism</a></p>

</div>
<?php ?>
